CXX = g++
EXT_DEPS = gdk-x11-3.0 gio-unix-2.0 gudev-1.0 xext libpulse-mainloop-glib
# don't include all the GLib headers inside the .d files
CXXFLAGS = -Wall -MMD -std=c++17 -iquote ./ \
	$(patsubst -I%,-isystem %,$(shell pkg-config --cflags $(EXT_DEPS)))
LDLIBS = $(shell pkg-config --libs $(EXT_DEPS))
# only the autogenerated files are in C
CC = gcc
CFLAGS = -Wall $(shell pkg-config --cflags gio-unix-2.0)
AUTOGEN_C_FILES = xidlechain_generated.c xidlechain_action_generated.c
AUTOGEN_HEADERS = ${AUTOGEN_C_FILES:.c=.h}
AUTOGEN_OBJECTS = ${AUTOGEN_C_FILES:.c=.o}
# This is only necessary because our C++ namespace is Xidlechain,
# and if we don't have a prefix then the codegen will create a struct
# whose name is also Xidlechain
AUTOGEN_C_NAMESPACE = C
AUTOGEN_PREFIX = io.github.maxerenberg.
COMMON_OBJECTS = event_manager.o activity_detector.o logind_manager.o \
	audio_detector.o process_spawner.o command.o config_manager.o \
	brightness_controller.o dbus_request_handler.o
OBJECTS = xidlechain.o $(COMMON_OBJECTS) $(AUTOGEN_OBJECTS)
DEPENDS = ${OBJECTS:.o=.d}
PREFIX = ~/.local

.PHONY: all autogen clean manpage install uninstall

all: xidlechain

# Some of the C++ files need the autogenerated header files, so those need to
# be built first
xidlechain: $(AUTOGEN_C_FILES) $(OBJECTS)
	$(CXX) -o $@ $(OBJECTS) $(LDLIBS)

# recompile if this file changed
#${OBJECTS}: Makefile

autogen: $(AUTOGEN_C_FILES)

xidlechain_generated.c: $(AUTOGEN_PREFIX)xidlechain.xml
	gdbus-codegen --generate-c-code $* --c-namespace $(AUTOGEN_C_NAMESPACE) --interface-prefix $(AUTOGEN_PREFIX) $<

xidlechain_action_generated.c: $(AUTOGEN_PREFIX)xidlechain.Action.xml
	gdbus-codegen --generate-c-code $* --c-namespace $(AUTOGEN_C_NAMESPACE) --c-generate-object-manager --interface-prefix $(AUTOGEN_PREFIX) $<

manpage:
	scdoc < xidlechain.1.scd > xidlechain.1

install: xidlechain manpage
	install -D -t ${PREFIX}/bin xidlechain
	install -D -t ${PREFIX}/share/man/man1 xidlechain.1
	mandb -u -q

uninstall:
	rm -f ${PREFIX}/bin/xidlechain
	rm -f ${PREFIX}/share/man/man1/xidlechain.1
	mandb -u -q

activity_detector_test: tests/activity_detector_test.o activity_detector.o
	${CXX} -o tests/$@ $^ `pkg-config --libs gdk-x11-3.0 xext`

logind_manager_test: tests/logind_manager_test.o logind_manager.o
	${CXX} -o tests/$@ $^ `pkg-config --libs gio-unix-2.0`

audio_detector_test: tests/audio_detector_test.o audio_detector.o
	${CXX} -o tests/$@ $^ `pkg-config --libs libpulse libpulse-mainloop-glib`

event_manager_test: tests/event_manager_test.o event_manager.o config_manager.o command.o
	${CXX} -o tests/$@ $^ `pkg-config --libs glib-2.0`

tests: activity_detector_test logind_manager_test audio_detector_test event_manager_test

-include ${DEPENDS}

clean:
	rm -f xidlechain xidlechain.1 *.o *.d
	rm -f $(AUTOGEN_C_FILES) $(AUTOGEN_HEADERS)
	rm -f tests/*_test tests/*.o
