name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: >-
        sudo apt update &&
        sudo apt install -y libgtk-3-dev libgudev-1.0-dev libxext-dev libpulse-dev libsystemd-dev g++ make
    - name: make
      run: make
    - name: event_manager_test
      run: >-
        make tests/event_manager_test &&
        tests/event_manager_test
